version: "3"
services:
  pg_forca:
    container_name: postgres_forca
    image: postgres
    environment: 
        POSTGRES_PASSWORD: postgres
    networks:
      - forca-network
    volumes:
      - /vol/forca/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"


networks:
  forca-network:
    driver: bridge
